"""initial

Revision ID: 11f43e1b1583
Revises: 
Create Date: 2026-06-09 20:48:45.266256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '11f43e1b1583'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('invoice_id', sa.Uuid(), nullable=True),
    sa.Column('event', sa.String(length=40), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_tenant_at', 'audit_events', ['tenant_id', 'created_at'], unique=False)
    op.create_table('tenants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('api_key_hash', sa.String(length=255), nullable=False),
    sa.Column('nit', sa.String(length=20), nullable=False),
    sa.Column('legal_name', sa.String(length=200), nullable=False),
    sa.Column('commercial_name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('postal_code', sa.String(length=10), nullable=False),
    sa.Column('municipio', sa.String(length=100), nullable=False),
    sa.Column('departamento', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('affiliation_iva', sa.String(length=10), nullable=False),
    sa.Column('establishment_code', sa.String(length=10), nullable=False),
    sa.Column('serie_fel', sa.String(length=20), nullable=False),
    sa.Column('contact_email', sa.String(length=254), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('provider_config', sa.JSON(), nullable=False),
    sa.Column('ambiente', sa.String(length=15), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('invoices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('external_ref', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('tipo_dte', sa.String(length=10), nullable=False),
    sa.Column('fecha_emision', sa.DateTime(timezone=True), nullable=False),
    sa.Column('moneda', sa.String(length=3), nullable=False),
    sa.Column('iva_incluido', sa.Boolean(), nullable=False),
    sa.Column('tasa_iva', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('request_payload', sa.JSON(), nullable=False),
    sa.Column('xml_local', sa.Text(), nullable=True),
    sa.Column('provider_response', sa.JSON(), nullable=True),
    sa.Column('uuid_sat', sa.String(length=64), nullable=True),
    sa.Column('serie', sa.String(length=20), nullable=True),
    sa.Column('numero_autorizacion', sa.String(length=64), nullable=True),
    sa.Column('fecha_certificacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('monto_iva', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('annulled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('annul_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'external_ref', 'status', name='uq_invoice_active_external_ref')
    )
    op.create_index('ix_invoice_tenant_created', 'invoices', ['tenant_id', 'created_at'], unique=False)
    op.create_index('ix_invoice_uuid_sat', 'invoices', ['uuid_sat'], unique=False)
    op.create_index(op.f('ix_invoices_external_ref'), 'invoices', ['external_ref'], unique=False)
    op.create_index(op.f('ix_invoices_status'), 'invoices', ['status'], unique=False)
    op.create_index(op.f('ix_invoices_tenant_id'), 'invoices', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoices_tenant_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_status'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_external_ref'), table_name='invoices')
    op.drop_index('ix_invoice_uuid_sat', table_name='invoices')
    op.drop_index('ix_invoice_tenant_created', table_name='invoices')
    op.drop_table('invoices')
    op.drop_table('tenants')
    op.drop_index('ix_audit_tenant_at', table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
